<?php
define("ELIZABETHAE_BASE_DIR", realpath(__DIR__."/../../"));
require_once 'PHPUnit/Framework.php';

require_once ELIZABETHAE_BASE_DIR.'/core/elizabethae.php';

/**
 * Test class for elizabethae.
 * Generated by PHPUnit on 2010-10-08 at 09:57:28.
 */
class elizabethaeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    elizabethae
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new \elizabethae\core\elizabethae("test");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testFind_plugin().
     */
    public function testFind_plugin()
    {
    }

}
?>
