<?php
define("APP_BASE_DIR", realpath(__DIR__."/../"));
define("ELIZABETHAE_BASE_DIR", realpath(__DIR__."/../../"));
require_once ELIZABETHAE_BASE_DIR . "/lib/bootstrap.php";
require_once 'PHPUnit/Framework.php';

require_once APP_BASE_DIR.'/controller/filterOnController.php';

/**
 * Test class for elizabethae.
 * Generated by PHPUnit on 2010-10-08 at 09:57:28.
 */
class filterOnControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    elizabethae
     * @access protected
     */
    protected $controller;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * mixin test.
     * call mixin_plugin function from controller
     */
    public function test_before_after_filter()
    {
        $controller = new elizabethae\controller\filterOnController("indexAction");
        $res = $controller->get_data();
        $this->assertEquals($res["res"], array("before", "after"));
    }



    public function test_filter_dependency1_test(){
        $controller = new elizabethae\controller\filterDependencyTest1OnController("indexAction");
        $res = $controller->get_data();
        $this->assertEquals($res["res"], array(
                "load_config",
                "load_page",
                "user_auth",
                "render",
                "conv_encode",
                "access_log"
            ));

    }

    public function test_filter_dependency2_test(){
        $controller = new elizabethae\controller\filterDependencyTest2OnController("indexAction");
        $res = $controller->get_data();
        $this->assertEquals($res["res"], array(
                "load_config",
                "load_page",
                "user_auth",
                "render",
                "conv_encode",
                "access_log"
            ));

    }

    public function test_filter_dependency3_test(){
        $controller = new elizabethae\controller\filterDependencyTest3OnController("indexAction");
        $res = $controller->get_data();
        $this->assertEquals($res["res"], array(
                "load_config",
                "load_page",
                "user_auth",
                "render",
                "conv_encode",
                "access_log"
            ));

    }
}