<?php
define("APP_BASE_DIR", realpath(__DIR__."/../"));
define("ELIZABETHAE_BASE_DIR", realpath(__DIR__."/../../"));
require_once ELIZABETHAE_BASE_DIR . "/lib/bootstrap.php";
require_once 'PHPUnit/Framework.php';

require_once APP_BASE_DIR.'/controller/pluginFilterController.php';

/**
 * Test class for elizabethae.
 * Generated by PHPUnit on 2010-10-08 at 09:57:28.
 */
class pluginFilterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    elizabethae
     * @access protected
     */
    protected $controller;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * plugin Filter Dependency test.
     */
    public function test_pluginFilterDependency()
    {
        $controller = new elizabethae\controller\pluginFilterController("indexAction");

        $res = $controller->get_data();
        $this->assertEquals($res["res"], array(
                "parse_mail",
                "load_config",
                "get_user",
                "render_mail",
                "send_mail",
                "write_mail_log"
            ));
    }

    public function test_arround_filter(){
        $controller = new elizabethae\controller\pluginArroundFilterController("indexAction");
        $res = $controller->get_data();
        $this->assertEquals($res["res"], array(
                "arround_filter(before_filter)",
                "arround_filter(after_filter)"
            ));
    }

}