<?php
require_once 'PHPUnit/Framework.php';

require_once '../../core/util/TopologicalSort.php';

/**
 * Test class for TopologicalSort.
 * Generated by PHPUnit on 2010-10-09 at 06:06:25.
 */
class TopologicalSortTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    TopologicalSort
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->ts = new elizabethae\util\TopologicalSort;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSort().
     */
    public function testSort1()
    {
        $classes = array('init' => array("require" => array(),
                                         "required" => array()),
                         'load_site' => array("require" => array("init"),
                                              "required" => array("load_page")),
                         'load_page' => array("required" => array("getUser"),
                                              "require" => array()),
                         'getUser' => array("require" => array(),
                                            "required" => array()));

        $this->ts->setNode($classes);
        $res = $this->ts->sort();
        $this->assertEquals($res, array("init", "load_site", "load_page", "getUser"));
    }

    public function testSort2(){
        $classes = array("getUser" => array("require" => array(),
                                            "required" => array()),
                         "init" => array("require" => array(),
                                         "required" => array()),
                         "hoge" => array("require" => array(),
                                         "required" => array()));

        $this->ts->setNode($classes);
        $res = $this->ts->sort();
        $ans = array("hoge", "init", "getUser");
        $this->assertEquals(sort($res), sort($ans));
    }

    public function testSort3(){
        $classes = array('init' => array("require" => array(),
                                         "required" => array()),
                         'load_site' => array("require" => array("init"),
                                              "required" => array()),
                         'load_page' => array("required" => array("getUser"),
                                              "require" => array()),
                         'getUser' => array("require" => array(),
                                            "required" => array()));

        $this->ts->setNode($classes);
        $res = $this->ts->sort();
        $this->assertLessThan(array_search('load_site', $res), array_search("init", $res));
        $this->assertLessThan(array_search("load_site", $res), array_search('getUser', $res));
    }

    public function testSort4(){
        $classes = array(
            'init' => array("require" => array(),
                "required" => array()),
            'getUser' => array("require" => array(),
                "required" => array()),
            'load_page' => array("required" => array("getUser"),
                "require" => array()),
            'load_site' => array("require" => array("init"),
                "required" => array()),
        );

        $this->ts->setNode($classes);
        $res = $this->ts->sort();
        $this->assertLessThan(array_search('load_site', $res), array_search("init", $res));
        $this->assertLessThan(array_search("load_site", $res), array_search('getUser', $res));
    }


    /**
     * @todo Implement testGetNewNode().
     */
    public function testGetNewNode()
    {
        $res = $this->ts->getNewNode("new_node_test");
        $this->assertEquals($res,
            array("name" => "new_node_test",
                "children" => array(),
                "parents" => array()));
    }

    public function testSort10()
    {
        $classes = array(
            "load_config" => array(
            ),
            "load_page" => array(
                "require" => "load_config",
            ),
            "interrupt_filter" => array(
                "require" => "load_config",
                "required" => "load_page"
            ),
            "user_auth" => array(
                "require" =>  "load_page"
            ),
        );

        $this->ts->setNode($classes);
        $res = $this->ts->sort();
        $this->assertEquals($res, array("load_config", "interrupt_filter", "load_page", "user_auth"));
    }

}
?>
